### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by yasharhon** [HelmerNylen/kons-screen#7]
Database files should be saved in a separate folder. The code must be adjusted to do this

**Comment by Acksell** [comment]
Sure, I thought of this but decided not to since the `update_db` function has to have access to the `APIs` module. What you would end up with in that case is just a `db` folder with a single file `db.json` inside. The real issue is instead the coupling of the function `update_db` and the `DB` class, these could instead be in separate files. I'll update this. 

I initially didn't do this because I thought it would be more readable to have the two related pieces of code in the same file to avoid jumping between several files just to understand a single contained concept.

**Comment by Acksell** [comment]
Guess I shouldn't close before the merge

**Comment by yasharhon** [comment]
Nice! I take it the idea is to let a single `DB` object handle all the information from the database and interaction with it, then. Personally I'm a bit skeptical to this approach, but this might be due to my background with SQL. We can definitely run with it for now.

If this is how we want to do it, an issue arises with the SL data, which should be a part of the same file. The code might need to be handled separately, though I haven't looked sufficiently at your code to be sure of this. I can have a look at how to integrate the SL data better into your code.

**Comment by Acksell** [comment]
I see your concerns, and I agree that there could be some benefits to splitting the database into several files. I am however also certain that the SL data is able to be integrated into the current solution. I think the problem is that you're using `urlretrieve` and passing a filepath argument and storing the data to that filepath. Instead of storing it immediately, you can return the data from that url and in `update_db.py` add another line in the `with` block like this

    with DB(DB_PATH) as db:
        db["facebook"]  = APIs.Facebook.get_group(fysiksektionen_group_id, limit=10)
        # etc. 
        db["SL"] = APIs.SL.get_SL_data( # necessary_arguments )

This comes with the benefit of also being able to parse the data before storing it.

Although making separate server endpoints for each API could be beneficial, I would like to have a working product before making such optimisations. Having a single endpoint requires less code to begin with which makes it faster and easier to deploy. Time for another meeting soon? :)

**Comment by Acksell** [comment]
Sidenote: I see that you've set up the server endpoint for the sl-data, nice! A request for data which resides on the server (I propose) should  be made from the pi-browser through javascript code, see the `getData` function in templates/index.html on my master branch: https://github.com/Acksell/kons-screen/blob/master/templates/index.html#L44
