### ISSUE TITLE
Improvement - Avoid global imports

### ISSUE THREAD

**Issue by yasharhon** [HelmerNylen/kons-screen#9]
The `from module import stuff` import style is currently implemented. This import style is discouraged in python, and should be changed to the `import module as name` style.

**Comment by yasharhon** [comment]
I am currently trying to fix it while adding the SL data code. Thus far I have found it used in APIs/__init__.py. Let me know if it is used anywhere else, and I can fix it. Or do it yourself, if you feel like it.

**Comment by yasharhon** [comment]
This is, by the way, a pure scope issue. It probably has no effect at all on the code itself, but is merely an issue of best practice.

**Comment by Acksell** [comment]
In the case of /APIs/\_\_init__.py the use of `from APIs.subdirectory import foo` is to remove the redundancy of specifying the `subdirectory` in `APIs.subdirectory.foo` since `subdirectory` only contains one file of interest (Facebook, Instagram, Calendar, FNewsfeed). Instead the API becomes a lot easier to use with just `APIs.foo`, for example APIs.Facebook, APIs.Instagram etc.

Are you suggesting using `import APIs.subdirectory.foo as foo` instead? To my knowledge this is identical to `from APIs.subdirectory import foo` in terms of namespace. I also consider the latter more readable.

If however `APIs.subdirectory` contained several files of interest then I would consider not reducing the namespace since you would want to group those related pieces of code together. Note that /APIs/\_\_init__.py would then be removed and you would change all of the `APIs.foo` references to `APIs.subdirectory.foo`.

I also don't think `from module import stuff` is discouraged per se other than in larger projects where there are an immense amount of references to different submodules and objects. The issue then becomes the ability to keep track of where something comes from when reading code. The files in this project are so small and the imports so few that you can see both the imports and the references without scrolling. It becomes an issue with files that are several hundred lines long. There is also the issue of name collisions

**Comment by Acksell** [comment]
Here is a statement on imports from [PEP8,](https://www.python.org/dev/peps/pep-0008/#imports) a python styleguide:

> * When importing a class from a class-containing module, it's usually okay to spell this:
>
>    `from myclass import MyClass`
>    `from foo.bar.yourclass import YourClass`
>If this spelling causes local name clashes, then spell them
>
>    `import myclass`
>    `import foo.bar.yourclass`
>and use `myclass.MyClass` and `foo.bar.yourclass.YourClass`.

**Comment by yasharhon** [comment]
I was indeed suggesting  `import APIs.subdirectory.foo as foo` instead, and it is completely true that in this case it would not have any effect.

When it comes to usability, one could also try `import APIs.subdirectory.foo`, in which case I believe the code would look exactly the same.

Your comment on what one could do if each subdirectory included multiple files is also interesting, though I'm unsure whether that is something we would want to do given the current structure.

I do, however, realise that the issue is nitpicky. If no one has any further comments, I have no complaints about closing it.
